# Generated by Django 5.0 on 2024-02-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Длительность тура'),
        ),
        migrations.AddField(
            model_name='tour',
            name='location',
            field=models.CharField(default=1, max_length=250, verbose_name='Локация'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='person',
            field=models.IntegerField(default=0, verbose_name='Количество людей'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='currency',
            field=models.CharField(choices=[('C', 'Som'), ('$', 'Dollar'), ('€', 'Euro')], default='C', max_length=100, verbose_name='Валюта'),
        ),
    ]
