# Generated by Django 5.0.1 on 2024-02-15 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
        ('tours', '0002_tour_duration_tour_location_tour_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='guides',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_guides', to='guides.guide', verbose_name='Гид'),
        ),
    ]
