# Generated by Django 5.0.1 on 2024-02-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
        ('tours', '0003_tour_guides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='guides',
        ),
        migrations.AddField(
            model_name='tour',
            name='guides',
            field=models.ManyToManyField(related_name='tour_guides', to='guides.guide', verbose_name='Гид'),
        ),
    ]
