# Generated by Django 5.0.1 on 2024-02-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('title', models.CharField(max_length=250, verbose_name='Должность')),
                ('image', models.ImageField(upload_to='guides_images', verbose_name='Картинка')),
                ('facebook', models.CharField(blank=True, max_length=250, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=250, verbose_name='Твиттер')),
                ('instagram', models.CharField(blank=True, max_length=250, verbose_name='Инстаграм')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Гид',
                'verbose_name_plural': 'Гиды',
            },
        ),
    ]
