# Generated by Django 5.0.1 on 2024-02-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('image', models.ImageField(upload_to='review_images', verbose_name='Фото')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
